name: eosl

channels:
  - conda-forge  # Ensures you get the latest stable packages
  - defaults

dependencies:
  - python=3.11
  - yfinance=0.2.54
  - pandas=2.2.3
  - matplotlib=3.10.0
  - scikit-learn=1.6.1 
  - plotly=6.0.0    
  - nbformat=5.10.4
  - autogluon-common=1.2              
  - autogluon-core=1.2              
  - autogluon-features=1.2              
  - autogluon-tabular=1.2              
  - autogluon-timeseries=1.2 
  - pyyaml=6.0.2 
  - fastdtw=0.3.4
  - seaborn=0.13.2
  - kneed=0.8.5
  - torch=2.5.1
  - pip  # Ensure pip is available
  - pip:
      - any-other-pip-package  # Add pip packages here if needed
